"""initial_schema_with_v1_columns

Revision ID: 2447b0018071
Revises: 
Create Date: 2026-09-23 21:13:29.028078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2447b0018071'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('max_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('calls_this_month', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_call_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('persona_description', sa.Text(), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('voice_id', sa.String(length=200), nullable=True),
    sa.Column('tts_provider', sa.String(length=50), nullable=False),
    sa.Column('stt_provider', sa.String(length=50), nullable=False),
    sa.Column('greeting_message', sa.Text(), nullable=True),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('working_hours', sa.Text(), nullable=True),
    sa.Column('tools_enabled', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_config_id'), 'agent_configs', ['config_id'], unique=True)
    op.create_index(op.f('ix_agent_configs_customer_id'), 'agent_configs', ['customer_id'], unique=False)
    op.create_table('call_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('room_name', sa.String(length=200), nullable=False),
    sa.Column('agent_identity', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('participant_sid', sa.String(length=200), nullable=True),
    sa.Column('participant_identity', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('call_type', sa.String(length=20), nullable=False),
    sa.Column('caller_number', sa.String(length=50), nullable=True),
    sa.Column('agent_config_id', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('call_cost_usd', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('transfer_target', sa.String(length=100), nullable=True),
    sa.Column('transfer_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_records_call_id'), 'call_records', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_records_customer_id'), 'call_records', ['customer_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('stt_characters', sa.Integer(), nullable=True),
    sa.Column('llm_tokens', sa.Integer(), nullable=True),
    sa.Column('tts_characters', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('stt_provider', sa.String(length=50), nullable=True),
    sa.Column('tts_provider', sa.String(length=50), nullable=True),
    sa.Column('stt_cost_usd', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('tts_cost_usd', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('llm_cost_usd', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_customer_id'), 'usage_logs', ['customer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=True)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    op.create_table('webhook_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('events', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_configs_customer_id'), 'webhook_configs', ['customer_id'], unique=False)
    op.create_table('agent_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Float(), nullable=True),
    sa.Column('tts_generated', sa.Boolean(), nullable=False),
    sa.Column('audio_duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_records.call_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_replies_call_id'), 'agent_replies', ['call_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('appointment_date', sa.String(length=50), nullable=False),
    sa.Column('appointment_time', sa.String(length=50), nullable=False),
    sa.Column('service_type', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('booked_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_by_agent', sa.Boolean(), nullable=False),
    sa.Column('appointment_uuid', sa.UUID(), nullable=False),
    sa.Column('reschedule_count', sa.Integer(), nullable=False),
    sa.Column('whatsapp_confirmation_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_records.call_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_uuid')
    )
    op.create_index(op.f('ix_appointments_call_id'), 'appointments', ['call_id'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call_records.call_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_chunks_call_id'), 'transcript_chunks', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_chunks_call_id'), table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index(op.f('ix_appointments_call_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_agent_replies_call_id'), table_name='agent_replies')
    op.drop_table('agent_replies')
    op.drop_index(op.f('ix_webhook_configs_customer_id'), table_name='webhook_configs')
    op.drop_table('webhook_configs')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_logs_customer_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_created_at'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_call_records_customer_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_call_id'), table_name='call_records')
    op.drop_table('call_records')
    op.drop_index(op.f('ix_agent_configs_customer_id'), table_name='agent_configs')
    op.drop_index(op.f('ix_agent_configs_config_id'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
